package com.isatk.model.dao;

import com.isatk.model.dto.CarFee;
import com.isatk.model.dto.CarFeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarFeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int countByExample(CarFeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int deleteByExample(CarFeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int insert(CarFee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int insertSelective(CarFee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	List<CarFee> selectByExample(CarFeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	CarFee selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int updateByExampleSelective(@Param("record") CarFee record,
			@Param("example") CarFeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int updateByExample(@Param("record") CarFee record,
			@Param("example") CarFeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int updateByPrimaryKeySelective(CarFee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	int updateByPrimaryKey(CarFee record);
}