package com.isatk.model.dao;

import com.isatk.model.dto.CargoDetails;
import com.isatk.model.dto.CargoDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CargoDetailsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int countByExample(CargoDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int deleteByExample(CargoDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int insert(CargoDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int insertSelective(CargoDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	List<CargoDetails> selectByExample(CargoDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	CargoDetails selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int updateByExampleSelective(@Param("record") CargoDetails record,
			@Param("example") CargoDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int updateByExample(@Param("record") CargoDetails record,
			@Param("example") CargoDetailsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int updateByPrimaryKeySelective(CargoDetails record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	int updateByPrimaryKey(CargoDetails record);
}