package com.isatk.model.dao;

import com.isatk.model.dto.CargoName;
import com.isatk.model.dto.CargoNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CargoNameMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int countByExample(CargoNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int deleteByExample(CargoNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int insert(CargoName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int insertSelective(CargoName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	List<CargoName> selectByExample(CargoNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	CargoName selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByExampleSelective(@Param("record") CargoName record,
			@Param("example") CargoNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByExample(@Param("record") CargoName record,
			@Param("example") CargoNameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByPrimaryKeySelective(CargoName record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByPrimaryKey(CargoName record);
}