package com.isatk.model.dao;

import com.isatk.model.dto.FaInvoiceDel;
import com.isatk.model.dto.FaInvoiceDelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FaInvoiceDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int countByExample(FaInvoiceDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int deleteByExample(FaInvoiceDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int insert(FaInvoiceDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int insertSelective(FaInvoiceDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    List<FaInvoiceDel> selectByExample(FaInvoiceDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    FaInvoiceDel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") FaInvoiceDel record, @Param("example") FaInvoiceDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int updateByExample(@Param("record") FaInvoiceDel record, @Param("example") FaInvoiceDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int updateByPrimaryKeySelective(FaInvoiceDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    int updateByPrimaryKey(FaInvoiceDel record);
}