package com.isatk.model.dao;

import com.isatk.model.dto.FaInvoice;
import com.isatk.model.dto.FaInvoiceExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface FaInvoiceMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int countByExample(FaInvoiceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int deleteByExample(FaInvoiceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int deleteByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int insert(FaInvoice record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int insertSelective(FaInvoice record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	List<FaInvoice> selectByExample(FaInvoiceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	FaInvoice selectByPrimaryKey(Long id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int updateByExampleSelective(@Param("record") FaInvoice record,
			@Param("example") FaInvoiceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int updateByExample(@Param("record") FaInvoice record,
			@Param("example") FaInvoiceExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int updateByPrimaryKeySelective(FaInvoice record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	int updateByPrimaryKey(FaInvoice record);
	int countByCondiction(FaInvoice record);
    List<FaInvoice> selectListByCondiction(FaInvoice record);
    
    int countDetail(FaInvoice record);
    List<FaInvoice> selectDetail(FaInvoice record);
    
    @Update("update fa_invoice set status=3 where id in ( #{ids} )")  
    int updateByIds(String ids);
    
    @Select("select max(id) from fa_invoice")
    Integer selectMaxId();
    
    List<Map> selectExcelDateByIds(@Param(value="ids") String ids);
    
    FaInvoice countDetail2(FaInvoice record);
    
}