package com.isatk.model.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.isatk.model.dto.SysUser;
import com.isatk.model.dto.SysUserExample;

public interface SysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int countByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int deleteByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	List<SysUser> selectByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	SysUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByExampleSelective(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByExample(@Param("record") SysUser record,
			@Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	int updateByPrimaryKey(SysUser record);

	int countByCondiction(SysUser record);
	
    List<SysUser> selectListByCondiction(SysUser record);
}