package com.isatk.model.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import com.isatk.ge.model.bean.Page;

public class BasClienteleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected Page page;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public BasClienteleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setPage(Page page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Page getPage() {
		return page;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andNickIsNull() {
			addCriterion("nick is null");
			return (Criteria) this;
		}

		public Criteria andNickIsNotNull() {
			addCriterion("nick is not null");
			return (Criteria) this;
		}

		public Criteria andNickEqualTo(String value) {
			addCriterion("nick =", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickNotEqualTo(String value) {
			addCriterion("nick <>", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickGreaterThan(String value) {
			addCriterion("nick >", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickGreaterThanOrEqualTo(String value) {
			addCriterion("nick >=", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickLessThan(String value) {
			addCriterion("nick <", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickLessThanOrEqualTo(String value) {
			addCriterion("nick <=", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickLike(String value) {
			addCriterion("nick like", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickNotLike(String value) {
			addCriterion("nick not like", value, "nick");
			return (Criteria) this;
		}

		public Criteria andNickIn(List<String> values) {
			addCriterion("nick in", values, "nick");
			return (Criteria) this;
		}

		public Criteria andNickNotIn(List<String> values) {
			addCriterion("nick not in", values, "nick");
			return (Criteria) this;
		}

		public Criteria andNickBetween(String value1, String value2) {
			addCriterion("nick between", value1, value2, "nick");
			return (Criteria) this;
		}

		public Criteria andNickNotBetween(String value1, String value2) {
			addCriterion("nick not between", value1, value2, "nick");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNull() {
			addCriterion("reg_time is null");
			return (Criteria) this;
		}

		public Criteria andRegTimeIsNotNull() {
			addCriterion("reg_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegTimeEqualTo(Date value) {
			addCriterion("reg_time =", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotEqualTo(Date value) {
			addCriterion("reg_time <>", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThan(Date value) {
			addCriterion("reg_time >", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_time >=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThan(Date value) {
			addCriterion("reg_time <", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeLessThanOrEqualTo(Date value) {
			addCriterion("reg_time <=", value, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeIn(List<Date> values) {
			addCriterion("reg_time in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotIn(List<Date> values) {
			addCriterion("reg_time not in", values, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeBetween(Date value1, Date value2) {
			addCriterion("reg_time between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andRegTimeNotBetween(Date value1, Date value2) {
			addCriterion("reg_time not between", value1, value2, "regTime");
			return (Criteria) this;
		}

		public Criteria andIsDisableIsNull() {
			addCriterion("is_disable is null");
			return (Criteria) this;
		}

		public Criteria andIsDisableIsNotNull() {
			addCriterion("is_disable is not null");
			return (Criteria) this;
		}

		public Criteria andIsDisableEqualTo(Integer value) {
			addCriterion("is_disable =", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotEqualTo(Integer value) {
			addCriterion("is_disable <>", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableGreaterThan(Integer value) {
			addCriterion("is_disable >", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_disable >=", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableLessThan(Integer value) {
			addCriterion("is_disable <", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableLessThanOrEqualTo(Integer value) {
			addCriterion("is_disable <=", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableIn(List<Integer> values) {
			addCriterion("is_disable in", values, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotIn(List<Integer> values) {
			addCriterion("is_disable not in", values, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableBetween(Integer value1, Integer value2) {
			addCriterion("is_disable between", value1, value2, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotBetween(Integer value1, Integer value2) {
			addCriterion("is_disable not between", value1, value2, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsSoIsNull() {
			addCriterion("is_so is null");
			return (Criteria) this;
		}

		public Criteria andIsSoIsNotNull() {
			addCriterion("is_so is not null");
			return (Criteria) this;
		}

		public Criteria andIsSoEqualTo(Integer value) {
			addCriterion("is_so =", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoNotEqualTo(Integer value) {
			addCriterion("is_so <>", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoGreaterThan(Integer value) {
			addCriterion("is_so >", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_so >=", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoLessThan(Integer value) {
			addCriterion("is_so <", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoLessThanOrEqualTo(Integer value) {
			addCriterion("is_so <=", value, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoIn(List<Integer> values) {
			addCriterion("is_so in", values, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoNotIn(List<Integer> values) {
			addCriterion("is_so not in", values, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoBetween(Integer value1, Integer value2) {
			addCriterion("is_so between", value1, value2, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsSoNotBetween(Integer value1, Integer value2) {
			addCriterion("is_so not between", value1, value2, "isSo");
			return (Criteria) this;
		}

		public Criteria andIsFaIsNull() {
			addCriterion("is_fa is null");
			return (Criteria) this;
		}

		public Criteria andIsFaIsNotNull() {
			addCriterion("is_fa is not null");
			return (Criteria) this;
		}

		public Criteria andIsFaEqualTo(Integer value) {
			addCriterion("is_fa =", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaNotEqualTo(Integer value) {
			addCriterion("is_fa <>", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaGreaterThan(Integer value) {
			addCriterion("is_fa >", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_fa >=", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaLessThan(Integer value) {
			addCriterion("is_fa <", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaLessThanOrEqualTo(Integer value) {
			addCriterion("is_fa <=", value, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaIn(List<Integer> values) {
			addCriterion("is_fa in", values, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaNotIn(List<Integer> values) {
			addCriterion("is_fa not in", values, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaBetween(Integer value1, Integer value2) {
			addCriterion("is_fa between", value1, value2, "isFa");
			return (Criteria) this;
		}

		public Criteria andIsFaNotBetween(Integer value1, Integer value2) {
			addCriterion("is_fa not between", value1, value2, "isFa");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNull() {
			addCriterion("bank_code is null");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNotNull() {
			addCriterion("bank_code is not null");
			return (Criteria) this;
		}

		public Criteria andBankCodeEqualTo(String value) {
			addCriterion("bank_code =", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotEqualTo(String value) {
			addCriterion("bank_code <>", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThan(String value) {
			addCriterion("bank_code >", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
			addCriterion("bank_code >=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThan(String value) {
			addCriterion("bank_code <", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThanOrEqualTo(String value) {
			addCriterion("bank_code <=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLike(String value) {
			addCriterion("bank_code like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotLike(String value) {
			addCriterion("bank_code not like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeIn(List<String> values) {
			addCriterion("bank_code in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotIn(List<String> values) {
			addCriterion("bank_code not in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeBetween(String value1, String value2) {
			addCriterion("bank_code between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotBetween(String value1, String value2) {
			addCriterion("bank_code not between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andCardNoIsNull() {
			addCriterion("card_no is null");
			return (Criteria) this;
		}

		public Criteria andCardNoIsNotNull() {
			addCriterion("card_no is not null");
			return (Criteria) this;
		}

		public Criteria andCardNoEqualTo(String value) {
			addCriterion("card_no =", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoNotEqualTo(String value) {
			addCriterion("card_no <>", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoGreaterThan(String value) {
			addCriterion("card_no >", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoGreaterThanOrEqualTo(String value) {
			addCriterion("card_no >=", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoLessThan(String value) {
			addCriterion("card_no <", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoLessThanOrEqualTo(String value) {
			addCriterion("card_no <=", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoLike(String value) {
			addCriterion("card_no like", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoNotLike(String value) {
			addCriterion("card_no not like", value, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoIn(List<String> values) {
			addCriterion("card_no in", values, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoNotIn(List<String> values) {
			addCriterion("card_no not in", values, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoBetween(String value1, String value2) {
			addCriterion("card_no between", value1, value2, "cardNo");
			return (Criteria) this;
		}

		public Criteria andCardNoNotBetween(String value1, String value2) {
			addCriterion("card_no not between", value1, value2, "cardNo");
			return (Criteria) this;
		}

		public Criteria andNameLikeInsensitive(String value) {
			addCriterion("upper(name) like", value.toUpperCase(), "name");
			return (Criteria) this;
		}

		public Criteria andPhoneLikeInsensitive(String value) {
			addCriterion("upper(phone) like", value.toUpperCase(), "phone");
			return (Criteria) this;
		}

		public Criteria andNickLikeInsensitive(String value) {
			addCriterion("upper(nick) like", value.toUpperCase(), "nick");
			return (Criteria) this;
		}

		public Criteria andBankCodeLikeInsensitive(String value) {
			addCriterion("upper(bank_code) like", value.toUpperCase(),
					"bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameLikeInsensitive(String value) {
			addCriterion("upper(bank_name) like", value.toUpperCase(),
					"bankName");
			return (Criteria) this;
		}

		public Criteria andCardNoLikeInsensitive(String value) {
			addCriterion("upper(card_no) like", value.toUpperCase(), "cardNo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bas_clientele
     *
     * @mbggenerated do_not_delete_during_merge Mon May 04 19:06:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}