package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

import com.isatk.model.dto.base.BaseDTO;

public class BasClientele extends BaseDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.id
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.phone
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.nick
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.reg_time
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private Date regTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_disable
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private Integer isDisable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_so
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private Integer isSo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.is_fa
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private Integer isFa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.bank_code
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.bank_name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bas_clientele.card_no
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private String cardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.id
	 * @return  the value of bas_clientele.id
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.id
	 * @param id  the value for bas_clientele.id
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.name
	 * @return  the value of bas_clientele.name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.name
	 * @param name  the value for bas_clientele.name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.phone
	 * @return  the value of bas_clientele.phone
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.phone
	 * @param phone  the value for bas_clientele.phone
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.nick
	 * @return  the value of bas_clientele.nick
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.nick
	 * @param nick  the value for bas_clientele.nick
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setNick(String nick) {
		this.nick = nick == null ? null : nick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.reg_time
	 * @return  the value of bas_clientele.reg_time
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.reg_time
	 * @param regTime  the value for bas_clientele.reg_time
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_disable
	 * @return  the value of bas_clientele.is_disable
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Integer getIsDisable() {
		return isDisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_disable
	 * @param isDisable  the value for bas_clientele.is_disable
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setIsDisable(Integer isDisable) {
		this.isDisable = isDisable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_so
	 * @return  the value of bas_clientele.is_so
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Integer getIsSo() {
		return isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_so
	 * @param isSo  the value for bas_clientele.is_so
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setIsSo(Integer isSo) {
		this.isSo = isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.is_fa
	 * @return  the value of bas_clientele.is_fa
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public Integer getIsFa() {
		return isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.is_fa
	 * @param isFa  the value for bas_clientele.is_fa
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setIsFa(Integer isFa) {
		this.isFa = isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.bank_code
	 * @return  the value of bas_clientele.bank_code
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.bank_code
	 * @param bankCode  the value for bas_clientele.bank_code
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode == null ? null : bankCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.bank_name
	 * @return  the value of bas_clientele.bank_name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.bank_name
	 * @param bankName  the value for bas_clientele.bank_name
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName == null ? null : bankName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bas_clientele.card_no
	 * @return  the value of bas_clientele.card_no
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bas_clientele.card_no
	 * @param cardNo  the value for bas_clientele.card_no
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo == null ? null : cardNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BasClientele other = (BasClientele) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getPhone() == null ? other.getPhone() == null : this
						.getPhone().equals(other.getPhone()))
				&& (this.getNick() == null ? other.getNick() == null : this
						.getNick().equals(other.getNick()))
				&& (this.getRegTime() == null ? other.getRegTime() == null
						: this.getRegTime().equals(other.getRegTime()))
				&& (this.getIsDisable() == null ? other.getIsDisable() == null
						: this.getIsDisable().equals(other.getIsDisable()))
				&& (this.getIsSo() == null ? other.getIsSo() == null : this
						.getIsSo().equals(other.getIsSo()))
				&& (this.getIsFa() == null ? other.getIsFa() == null : this
						.getIsFa().equals(other.getIsFa()))
				&& (this.getBankCode() == null ? other.getBankCode() == null
						: this.getBankCode().equals(other.getBankCode()))
				&& (this.getBankName() == null ? other.getBankName() == null
						: this.getBankName().equals(other.getBankName()))
				&& (this.getCardNo() == null ? other.getCardNo() == null : this
						.getCardNo().equals(other.getCardNo()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bas_clientele
	 * @mbggenerated  Mon Jun 01 16:58:06 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getPhone() == null) ? 0 : getPhone().hashCode());
		result = prime * result
				+ ((getNick() == null) ? 0 : getNick().hashCode());
		result = prime * result
				+ ((getRegTime() == null) ? 0 : getRegTime().hashCode());
		result = prime * result
				+ ((getIsDisable() == null) ? 0 : getIsDisable().hashCode());
		result = prime * result
				+ ((getIsSo() == null) ? 0 : getIsSo().hashCode());
		result = prime * result
				+ ((getIsFa() == null) ? 0 : getIsFa().hashCode());
		result = prime * result
				+ ((getBankCode() == null) ? 0 : getBankCode().hashCode());
		result = prime * result
				+ ((getBankName() == null) ? 0 : getBankName().hashCode());
		result = prime * result
				+ ((getCardNo() == null) ? 0 : getCardNo().hashCode());
		return result;
	}
}