package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

public class BasOrganize implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.org_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.org_code
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.org_name
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.org_address
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String orgAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.manager_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.introduction
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.url_logo
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String urlLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.remark
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.org_key
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String orgKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.is_online
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.is_outline
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Integer isOutline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.time_start
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Date timeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.time_end
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Date timeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.status
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.user_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Long userCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.time_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Date timeCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.time_update
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private Date timeUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bas_organize.guids
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private String guids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bas_organize
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.org_id
     *
     * @return the value of bas_organize.org_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.org_id
     *
     * @param orgId the value for bas_organize.org_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.org_code
     *
     * @return the value of bas_organize.org_code
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.org_code
     *
     * @param orgCode the value for bas_organize.org_code
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.org_name
     *
     * @return the value of bas_organize.org_name
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.org_name
     *
     * @param orgName the value for bas_organize.org_name
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.org_address
     *
     * @return the value of bas_organize.org_address
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getOrgAddress() {
        return orgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.org_address
     *
     * @param orgAddress the value for bas_organize.org_address
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress == null ? null : orgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.manager_id
     *
     * @return the value of bas_organize.manager_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.manager_id
     *
     * @param managerId the value for bas_organize.manager_id
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.introduction
     *
     * @return the value of bas_organize.introduction
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.introduction
     *
     * @param introduction the value for bas_organize.introduction
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.url_logo
     *
     * @return the value of bas_organize.url_logo
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getUrlLogo() {
        return urlLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.url_logo
     *
     * @param urlLogo the value for bas_organize.url_logo
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setUrlLogo(String urlLogo) {
        this.urlLogo = urlLogo == null ? null : urlLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.remark
     *
     * @return the value of bas_organize.remark
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.remark
     *
     * @param remark the value for bas_organize.remark
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.org_key
     *
     * @return the value of bas_organize.org_key
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getOrgKey() {
        return orgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.org_key
     *
     * @param orgKey the value for bas_organize.org_key
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setOrgKey(String orgKey) {
        this.orgKey = orgKey == null ? null : orgKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.is_online
     *
     * @return the value of bas_organize.is_online
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.is_online
     *
     * @param isOnline the value for bas_organize.is_online
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.is_outline
     *
     * @return the value of bas_organize.is_outline
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Integer getIsOutline() {
        return isOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.is_outline
     *
     * @param isOutline the value for bas_organize.is_outline
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setIsOutline(Integer isOutline) {
        this.isOutline = isOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.time_start
     *
     * @return the value of bas_organize.time_start
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Date getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.time_start
     *
     * @param timeStart the value for bas_organize.time_start
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.time_end
     *
     * @return the value of bas_organize.time_end
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.time_end
     *
     * @param timeEnd the value for bas_organize.time_end
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.status
     *
     * @return the value of bas_organize.status
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.status
     *
     * @param status the value for bas_organize.status
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.user_create
     *
     * @return the value of bas_organize.user_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Long getUserCreate() {
        return userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.user_create
     *
     * @param userCreate the value for bas_organize.user_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setUserCreate(Long userCreate) {
        this.userCreate = userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.time_create
     *
     * @return the value of bas_organize.time_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Date getTimeCreate() {
        return timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.time_create
     *
     * @param timeCreate the value for bas_organize.time_create
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setTimeCreate(Date timeCreate) {
        this.timeCreate = timeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.time_update
     *
     * @return the value of bas_organize.time_update
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public Date getTimeUpdate() {
        return timeUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.time_update
     *
     * @param timeUpdate the value for bas_organize.time_update
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setTimeUpdate(Date timeUpdate) {
        this.timeUpdate = timeUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bas_organize.guids
     *
     * @return the value of bas_organize.guids
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public String getGuids() {
        return guids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bas_organize.guids
     *
     * @param guids the value for bas_organize.guids
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    public void setGuids(String guids) {
        this.guids = guids == null ? null : guids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_organize
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BasOrganize other = (BasOrganize) that;
        return (this.getOrgId() == null ? other.getOrgId() == null : this.getOrgId().equals(other.getOrgId()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getOrgAddress() == null ? other.getOrgAddress() == null : this.getOrgAddress().equals(other.getOrgAddress()))
            && (this.getManagerId() == null ? other.getManagerId() == null : this.getManagerId().equals(other.getManagerId()))
            && (this.getIntroduction() == null ? other.getIntroduction() == null : this.getIntroduction().equals(other.getIntroduction()))
            && (this.getUrlLogo() == null ? other.getUrlLogo() == null : this.getUrlLogo().equals(other.getUrlLogo()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getOrgKey() == null ? other.getOrgKey() == null : this.getOrgKey().equals(other.getOrgKey()))
            && (this.getIsOnline() == null ? other.getIsOnline() == null : this.getIsOnline().equals(other.getIsOnline()))
            && (this.getIsOutline() == null ? other.getIsOutline() == null : this.getIsOutline().equals(other.getIsOutline()))
            && (this.getTimeStart() == null ? other.getTimeStart() == null : this.getTimeStart().equals(other.getTimeStart()))
            && (this.getTimeEnd() == null ? other.getTimeEnd() == null : this.getTimeEnd().equals(other.getTimeEnd()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUserCreate() == null ? other.getUserCreate() == null : this.getUserCreate().equals(other.getUserCreate()))
            && (this.getTimeCreate() == null ? other.getTimeCreate() == null : this.getTimeCreate().equals(other.getTimeCreate()))
            && (this.getTimeUpdate() == null ? other.getTimeUpdate() == null : this.getTimeUpdate().equals(other.getTimeUpdate()))
            && (this.getGuids() == null ? other.getGuids() == null : this.getGuids().equals(other.getGuids()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bas_organize
     *
     * @mbggenerated Fri Apr 10 16:36:02 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrgId() == null) ? 0 : getOrgId().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getOrgAddress() == null) ? 0 : getOrgAddress().hashCode());
        result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
        result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
        result = prime * result + ((getUrlLogo() == null) ? 0 : getUrlLogo().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getOrgKey() == null) ? 0 : getOrgKey().hashCode());
        result = prime * result + ((getIsOnline() == null) ? 0 : getIsOnline().hashCode());
        result = prime * result + ((getIsOutline() == null) ? 0 : getIsOutline().hashCode());
        result = prime * result + ((getTimeStart() == null) ? 0 : getTimeStart().hashCode());
        result = prime * result + ((getTimeEnd() == null) ? 0 : getTimeEnd().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUserCreate() == null) ? 0 : getUserCreate().hashCode());
        result = prime * result + ((getTimeCreate() == null) ? 0 : getTimeCreate().hashCode());
        result = prime * result + ((getTimeUpdate() == null) ? 0 : getTimeUpdate().hashCode());
        result = prime * result + ((getGuids() == null) ? 0 : getGuids().hashCode());
        return result;
    }
}