package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

import com.isatk.model.dto.base.BaseDTO;

public class Car extends BaseDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.Id
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.code
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ins_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    private Date insDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.up_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    private Date upDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Id
     *
     * @return the value of car.Id
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Id
     *
     * @param id the value for car.Id
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.code
     *
     * @return the value of car.code
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.code
     *
     * @param code the value for car.code
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ins_date
     *
     * @return the value of car.ins_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ins_date
     *
     * @param insDate the value for car.ins_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.up_date
     *
     * @return the value of car.up_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public Date getUpDate() {
        return upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.up_date
     *
     * @param upDate the value for car.up_date
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    public void setUpDate(Date upDate) {
        this.upDate = upDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Car other = (Car) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getInsDate() == null ? other.getInsDate() == null : this.getInsDate().equals(other.getInsDate()))
            && (this.getUpDate() == null ? other.getUpDate() == null : this.getUpDate().equals(other.getUpDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbggenerated Sat May 23 10:17:07 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getInsDate() == null) ? 0 : getInsDate().hashCode());
        result = prime * result + ((getUpDate() == null) ? 0 : getUpDate().hashCode());
        return result;
    }
    
    
    private CarFee sumCarFee;

	public CarFee getSumCarFee() {
		return sumCarFee;
	}

	public void setSumCarFee(CarFee sumCarFee) {
		this.sumCarFee = sumCarFee;
	}
    
}