package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

import com.isatk.model.dto.base.BaseDTO;

public class CarFee  extends BaseDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.gas
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer gas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.tolls
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer tolls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.water
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer water;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.engine_oil
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer engineOil;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.service
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer service;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.butter
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer butter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.other
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Integer other;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.remark
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.car_id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Long carId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column car_fee.ins_date
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private Date insDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.id
	 * @return  the value of car_fee.id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.id
	 * @param id  the value for car_fee.id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.gas
	 * @return  the value of car_fee.gas
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getGas() {
		return gas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.gas
	 * @param gas  the value for car_fee.gas
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setGas(Integer gas) {
		this.gas = gas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.tolls
	 * @return  the value of car_fee.tolls
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getTolls() {
		return tolls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.tolls
	 * @param tolls  the value for car_fee.tolls
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setTolls(Integer tolls) {
		this.tolls = tolls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.water
	 * @return  the value of car_fee.water
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getWater() {
		return water;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.water
	 * @param water  the value for car_fee.water
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setWater(Integer water) {
		this.water = water;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.engine_oil
	 * @return  the value of car_fee.engine_oil
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getEngineOil() {
		return engineOil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.engine_oil
	 * @param engineOil  the value for car_fee.engine_oil
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setEngineOil(Integer engineOil) {
		this.engineOil = engineOil;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.service
	 * @return  the value of car_fee.service
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getService() {
		return service;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.service
	 * @param service  the value for car_fee.service
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setService(Integer service) {
		this.service = service;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.butter
	 * @return  the value of car_fee.butter
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getButter() {
		return butter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.butter
	 * @param butter  the value for car_fee.butter
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setButter(Integer butter) {
		this.butter = butter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.other
	 * @return  the value of car_fee.other
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Integer getOther() {
		return other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.other
	 * @param other  the value for car_fee.other
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setOther(Integer other) {
		this.other = other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.remark
	 * @return  the value of car_fee.remark
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.remark
	 * @param remark  the value for car_fee.remark
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.car_id
	 * @return  the value of car_fee.car_id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Long getCarId() {
		return carId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.car_id
	 * @param carId  the value for car_fee.car_id
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setCarId(Long carId) {
		this.carId = carId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column car_fee.ins_date
	 * @return  the value of car_fee.ins_date
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public Date getInsDate() {
		return insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column car_fee.ins_date
	 * @param insDate  the value for car_fee.ins_date
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CarFee other = (CarFee) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getGas() == null ? other.getGas() == null : this
						.getGas().equals(other.getGas()))
				&& (this.getTolls() == null ? other.getTolls() == null : this
						.getTolls().equals(other.getTolls()))
				&& (this.getWater() == null ? other.getWater() == null : this
						.getWater().equals(other.getWater()))
				&& (this.getEngineOil() == null ? other.getEngineOil() == null
						: this.getEngineOil().equals(other.getEngineOil()))
				&& (this.getService() == null ? other.getService() == null
						: this.getService().equals(other.getService()))
				&& (this.getButter() == null ? other.getButter() == null : this
						.getButter().equals(other.getButter()))
				&& (this.getOther() == null ? other.getOther() == null : this
						.getOther().equals(other.getOther()))
				&& (this.getRemark() == null ? other.getRemark() == null : this
						.getRemark().equals(other.getRemark()))
				&& (this.getCarId() == null ? other.getCarId() == null : this
						.getCarId().equals(other.getCarId()))
				&& (this.getInsDate() == null ? other.getInsDate() == null
						: this.getInsDate().equals(other.getInsDate()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table car_fee
	 * @mbggenerated  Sat May 23 10:51:13 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getGas() == null) ? 0 : getGas().hashCode());
		result = prime * result
				+ ((getTolls() == null) ? 0 : getTolls().hashCode());
		result = prime * result
				+ ((getWater() == null) ? 0 : getWater().hashCode());
		result = prime * result
				+ ((getEngineOil() == null) ? 0 : getEngineOil().hashCode());
		result = prime * result
				+ ((getService() == null) ? 0 : getService().hashCode());
		result = prime * result
				+ ((getButter() == null) ? 0 : getButter().hashCode());
		result = prime * result
				+ ((getOther() == null) ? 0 : getOther().hashCode());
		result = prime * result
				+ ((getRemark() == null) ? 0 : getRemark().hashCode());
		result = prime * result
				+ ((getCarId() == null) ? 0 : getCarId().hashCode());
		result = prime * result
				+ ((getInsDate() == null) ? 0 : getInsDate().hashCode());
		return result;
	}
}