package com.isatk.model.dto;

import java.io.Serializable;

public class CargoDetails implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo_details.id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo_details.name
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo_details.insurance
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private Integer insurance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo_details.num
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private String num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cargo_details.fa_id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private Long faId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo_details.id
	 * @return  the value of cargo_details.id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo_details.id
	 * @param id  the value for cargo_details.id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo_details.name
	 * @return  the value of cargo_details.name
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo_details.name
	 * @param name  the value for cargo_details.name
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo_details.insurance
	 * @return  the value of cargo_details.insurance
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public Integer getInsurance() {
		return insurance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo_details.insurance
	 * @param insurance  the value for cargo_details.insurance
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public void setInsurance(Integer insurance) {
		this.insurance = insurance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo_details.num
	 * @return  the value of cargo_details.num
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public String getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo_details.num
	 * @param num  the value for cargo_details.num
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public void setNum(String num) {
		this.num = num == null ? null : num.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cargo_details.fa_id
	 * @return  the value of cargo_details.fa_id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public Long getFaId() {
		return faId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cargo_details.fa_id
	 * @param faId  the value for cargo_details.fa_id
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	public void setFaId(Long faId) {
		this.faId = faId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CargoDetails other = (CargoDetails) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getInsurance() == null ? other.getInsurance() == null
						: this.getInsurance().equals(other.getInsurance()))
				&& (this.getNum() == null ? other.getNum() == null : this
						.getNum().equals(other.getNum()))
				&& (this.getFaId() == null ? other.getFaId() == null : this
						.getFaId().equals(other.getFaId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cargo_details
	 * @mbggenerated  Sun May 10 19:46:09 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getInsurance() == null) ? 0 : getInsurance().hashCode());
		result = prime * result
				+ ((getNum() == null) ? 0 : getNum().hashCode());
		result = prime * result
				+ ((getFaId() == null) ? 0 : getFaId().hashCode());
		return result;
	}
}