package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;

import com.isatk.model.dto.base.BaseDTO;

public class FaInvoiceDel extends BaseDTO  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String faNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date faTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String faPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long faPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long faClientele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String soPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long soClientele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long soPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.freight
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.collection
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer collection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.ins_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date insTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.up_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.status
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.count_insurance
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer countInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fee
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.freight_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer freightWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.collection_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer collectionWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.bank_code
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.card_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer soWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.fa_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String faName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String soName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_point_sub_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String soPointSubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_point_sub_money
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer soPointSubMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.so_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date soTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.collection_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date collectionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.cargo_num
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Integer cargoNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.del_user_id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Long delUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.del_date
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private Date delDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fa_invoice_del.del_user_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private String delUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.id
     *
     * @return the value of fa_invoice_del.id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.id
     *
     * @param id the value for fa_invoice_del.id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_no
     *
     * @return the value of fa_invoice_del.fa_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getFaNo() {
        return faNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_no
     *
     * @param faNo the value for fa_invoice_del.fa_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaNo(String faNo) {
        this.faNo = faNo == null ? null : faNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_time
     *
     * @return the value of fa_invoice_del.fa_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getFaTime() {
        return faTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_time
     *
     * @param faTime the value for fa_invoice_del.fa_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaTime(Date faTime) {
        this.faTime = faTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_phone
     *
     * @return the value of fa_invoice_del.fa_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getFaPhone() {
        return faPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_phone
     *
     * @param faPhone the value for fa_invoice_del.fa_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaPhone(String faPhone) {
        this.faPhone = faPhone == null ? null : faPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_point
     *
     * @return the value of fa_invoice_del.fa_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getFaPoint() {
        return faPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_point
     *
     * @param faPoint the value for fa_invoice_del.fa_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaPoint(Long faPoint) {
        this.faPoint = faPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_clientele
     *
     * @return the value of fa_invoice_del.fa_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getFaClientele() {
        return faClientele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_clientele
     *
     * @param faClientele the value for fa_invoice_del.fa_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaClientele(Long faClientele) {
        this.faClientele = faClientele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_phone
     *
     * @return the value of fa_invoice_del.so_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getSoPhone() {
        return soPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_phone
     *
     * @param soPhone the value for fa_invoice_del.so_phone
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoPhone(String soPhone) {
        this.soPhone = soPhone == null ? null : soPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_clientele
     *
     * @return the value of fa_invoice_del.so_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getSoClientele() {
        return soClientele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_clientele
     *
     * @param soClientele the value for fa_invoice_del.so_clientele
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoClientele(Long soClientele) {
        this.soClientele = soClientele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_point
     *
     * @return the value of fa_invoice_del.so_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getSoPoint() {
        return soPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_point
     *
     * @param soPoint the value for fa_invoice_del.so_point
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoPoint(Long soPoint) {
        this.soPoint = soPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.freight
     *
     * @return the value of fa_invoice_del.freight
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.freight
     *
     * @param freight the value for fa_invoice_del.freight
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.collection
     *
     * @return the value of fa_invoice_del.collection
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getCollection() {
        return collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.collection
     *
     * @param collection the value for fa_invoice_del.collection
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCollection(Integer collection) {
        this.collection = collection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.ins_time
     *
     * @return the value of fa_invoice_del.ins_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getInsTime() {
        return insTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.ins_time
     *
     * @param insTime the value for fa_invoice_del.ins_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setInsTime(Date insTime) {
        this.insTime = insTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.up_time
     *
     * @return the value of fa_invoice_del.up_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.up_time
     *
     * @param upTime the value for fa_invoice_del.up_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.status
     *
     * @return the value of fa_invoice_del.status
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.status
     *
     * @param status the value for fa_invoice_del.status
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.count_insurance
     *
     * @return the value of fa_invoice_del.count_insurance
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getCountInsurance() {
        return countInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.count_insurance
     *
     * @param countInsurance the value for fa_invoice_del.count_insurance
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCountInsurance(Integer countInsurance) {
        this.countInsurance = countInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fee
     *
     * @return the value of fa_invoice_del.fee
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fee
     *
     * @param fee the value for fa_invoice_del.fee
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.freight_way
     *
     * @return the value of fa_invoice_del.freight_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getFreightWay() {
        return freightWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.freight_way
     *
     * @param freightWay the value for fa_invoice_del.freight_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFreightWay(Integer freightWay) {
        this.freightWay = freightWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.collection_way
     *
     * @return the value of fa_invoice_del.collection_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getCollectionWay() {
        return collectionWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.collection_way
     *
     * @param collectionWay the value for fa_invoice_del.collection_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCollectionWay(Integer collectionWay) {
        this.collectionWay = collectionWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.bank_code
     *
     * @return the value of fa_invoice_del.bank_code
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.bank_code
     *
     * @param bankCode the value for fa_invoice_del.bank_code
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.card_no
     *
     * @return the value of fa_invoice_del.card_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.card_no
     *
     * @param cardNo the value for fa_invoice_del.card_no
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_way
     *
     * @return the value of fa_invoice_del.so_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getSoWay() {
        return soWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_way
     *
     * @param soWay the value for fa_invoice_del.so_way
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoWay(Integer soWay) {
        this.soWay = soWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.fa_name
     *
     * @return the value of fa_invoice_del.fa_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getFaName() {
        return faName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.fa_name
     *
     * @param faName the value for fa_invoice_del.fa_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setFaName(String faName) {
        this.faName = faName == null ? null : faName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_name
     *
     * @return the value of fa_invoice_del.so_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getSoName() {
        return soName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_name
     *
     * @param soName the value for fa_invoice_del.so_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoName(String soName) {
        this.soName = soName == null ? null : soName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_point_sub_name
     *
     * @return the value of fa_invoice_del.so_point_sub_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getSoPointSubName() {
        return soPointSubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_point_sub_name
     *
     * @param soPointSubName the value for fa_invoice_del.so_point_sub_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoPointSubName(String soPointSubName) {
        this.soPointSubName = soPointSubName == null ? null : soPointSubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_point_sub_money
     *
     * @return the value of fa_invoice_del.so_point_sub_money
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getSoPointSubMoney() {
        return soPointSubMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_point_sub_money
     *
     * @param soPointSubMoney the value for fa_invoice_del.so_point_sub_money
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoPointSubMoney(Integer soPointSubMoney) {
        this.soPointSubMoney = soPointSubMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.so_time
     *
     * @return the value of fa_invoice_del.so_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getSoTime() {
        return soTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.so_time
     *
     * @param soTime the value for fa_invoice_del.so_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setSoTime(Date soTime) {
        this.soTime = soTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.collection_time
     *
     * @return the value of fa_invoice_del.collection_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getCollectionTime() {
        return collectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.collection_time
     *
     * @param collectionTime the value for fa_invoice_del.collection_time
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCollectionTime(Date collectionTime) {
        this.collectionTime = collectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.cargo_num
     *
     * @return the value of fa_invoice_del.cargo_num
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Integer getCargoNum() {
        return cargoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.cargo_num
     *
     * @param cargoNum the value for fa_invoice_del.cargo_num
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setCargoNum(Integer cargoNum) {
        this.cargoNum = cargoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.del_user_id
     *
     * @return the value of fa_invoice_del.del_user_id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Long getDelUserId() {
        return delUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.del_user_id
     *
     * @param delUserId the value for fa_invoice_del.del_user_id
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setDelUserId(Long delUserId) {
        this.delUserId = delUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.del_date
     *
     * @return the value of fa_invoice_del.del_date
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.del_date
     *
     * @param delDate the value for fa_invoice_del.del_date
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fa_invoice_del.del_user_name
     *
     * @return the value of fa_invoice_del.del_user_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public String getDelUserName() {
        return delUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fa_invoice_del.del_user_name
     *
     * @param delUserName the value for fa_invoice_del.del_user_name
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    public void setDelUserName(String delUserName) {
        this.delUserName = delUserName == null ? null : delUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FaInvoiceDel other = (FaInvoiceDel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFaNo() == null ? other.getFaNo() == null : this.getFaNo().equals(other.getFaNo()))
            && (this.getFaTime() == null ? other.getFaTime() == null : this.getFaTime().equals(other.getFaTime()))
            && (this.getFaPhone() == null ? other.getFaPhone() == null : this.getFaPhone().equals(other.getFaPhone()))
            && (this.getFaPoint() == null ? other.getFaPoint() == null : this.getFaPoint().equals(other.getFaPoint()))
            && (this.getFaClientele() == null ? other.getFaClientele() == null : this.getFaClientele().equals(other.getFaClientele()))
            && (this.getSoPhone() == null ? other.getSoPhone() == null : this.getSoPhone().equals(other.getSoPhone()))
            && (this.getSoClientele() == null ? other.getSoClientele() == null : this.getSoClientele().equals(other.getSoClientele()))
            && (this.getSoPoint() == null ? other.getSoPoint() == null : this.getSoPoint().equals(other.getSoPoint()))
            && (this.getFreight() == null ? other.getFreight() == null : this.getFreight().equals(other.getFreight()))
            && (this.getCollection() == null ? other.getCollection() == null : this.getCollection().equals(other.getCollection()))
            && (this.getInsTime() == null ? other.getInsTime() == null : this.getInsTime().equals(other.getInsTime()))
            && (this.getUpTime() == null ? other.getUpTime() == null : this.getUpTime().equals(other.getUpTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCountInsurance() == null ? other.getCountInsurance() == null : this.getCountInsurance().equals(other.getCountInsurance()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getFreightWay() == null ? other.getFreightWay() == null : this.getFreightWay().equals(other.getFreightWay()))
            && (this.getCollectionWay() == null ? other.getCollectionWay() == null : this.getCollectionWay().equals(other.getCollectionWay()))
            && (this.getBankCode() == null ? other.getBankCode() == null : this.getBankCode().equals(other.getBankCode()))
            && (this.getCardNo() == null ? other.getCardNo() == null : this.getCardNo().equals(other.getCardNo()))
            && (this.getSoWay() == null ? other.getSoWay() == null : this.getSoWay().equals(other.getSoWay()))
            && (this.getFaName() == null ? other.getFaName() == null : this.getFaName().equals(other.getFaName()))
            && (this.getSoName() == null ? other.getSoName() == null : this.getSoName().equals(other.getSoName()))
            && (this.getSoPointSubName() == null ? other.getSoPointSubName() == null : this.getSoPointSubName().equals(other.getSoPointSubName()))
            && (this.getSoPointSubMoney() == null ? other.getSoPointSubMoney() == null : this.getSoPointSubMoney().equals(other.getSoPointSubMoney()))
            && (this.getSoTime() == null ? other.getSoTime() == null : this.getSoTime().equals(other.getSoTime()))
            && (this.getCollectionTime() == null ? other.getCollectionTime() == null : this.getCollectionTime().equals(other.getCollectionTime()))
            && (this.getCargoNum() == null ? other.getCargoNum() == null : this.getCargoNum().equals(other.getCargoNum()))
            && (this.getDelUserId() == null ? other.getDelUserId() == null : this.getDelUserId().equals(other.getDelUserId()))
            && (this.getDelDate() == null ? other.getDelDate() == null : this.getDelDate().equals(other.getDelDate()))
            && (this.getDelUserName() == null ? other.getDelUserName() == null : this.getDelUserName().equals(other.getDelUserName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fa_invoice_del
     *
     * @mbggenerated Mon Oct 19 22:20:43 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFaNo() == null) ? 0 : getFaNo().hashCode());
        result = prime * result + ((getFaTime() == null) ? 0 : getFaTime().hashCode());
        result = prime * result + ((getFaPhone() == null) ? 0 : getFaPhone().hashCode());
        result = prime * result + ((getFaPoint() == null) ? 0 : getFaPoint().hashCode());
        result = prime * result + ((getFaClientele() == null) ? 0 : getFaClientele().hashCode());
        result = prime * result + ((getSoPhone() == null) ? 0 : getSoPhone().hashCode());
        result = prime * result + ((getSoClientele() == null) ? 0 : getSoClientele().hashCode());
        result = prime * result + ((getSoPoint() == null) ? 0 : getSoPoint().hashCode());
        result = prime * result + ((getFreight() == null) ? 0 : getFreight().hashCode());
        result = prime * result + ((getCollection() == null) ? 0 : getCollection().hashCode());
        result = prime * result + ((getInsTime() == null) ? 0 : getInsTime().hashCode());
        result = prime * result + ((getUpTime() == null) ? 0 : getUpTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCountInsurance() == null) ? 0 : getCountInsurance().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getFreightWay() == null) ? 0 : getFreightWay().hashCode());
        result = prime * result + ((getCollectionWay() == null) ? 0 : getCollectionWay().hashCode());
        result = prime * result + ((getBankCode() == null) ? 0 : getBankCode().hashCode());
        result = prime * result + ((getCardNo() == null) ? 0 : getCardNo().hashCode());
        result = prime * result + ((getSoWay() == null) ? 0 : getSoWay().hashCode());
        result = prime * result + ((getFaName() == null) ? 0 : getFaName().hashCode());
        result = prime * result + ((getSoName() == null) ? 0 : getSoName().hashCode());
        result = prime * result + ((getSoPointSubName() == null) ? 0 : getSoPointSubName().hashCode());
        result = prime * result + ((getSoPointSubMoney() == null) ? 0 : getSoPointSubMoney().hashCode());
        result = prime * result + ((getSoTime() == null) ? 0 : getSoTime().hashCode());
        result = prime * result + ((getCollectionTime() == null) ? 0 : getCollectionTime().hashCode());
        result = prime * result + ((getCargoNum() == null) ? 0 : getCargoNum().hashCode());
        result = prime * result + ((getDelUserId() == null) ? 0 : getDelUserId().hashCode());
        result = prime * result + ((getDelDate() == null) ? 0 : getDelDate().hashCode());
        result = prime * result + ((getDelUserName() == null) ? 0 : getDelUserName().hashCode());
        return result;
    }
}