package com.isatk.model.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.isatk.model.dto.base.BaseDTO;

public class FaInvoice extends BaseDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.id
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String faNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Date faTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String faPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Long faPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Long faClientele;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String soPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Long soClientele;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Long soPoint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.freight
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer freight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.collection
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer collection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.ins_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Date insTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.up_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Date upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.status
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.count_insurance
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer countInsurance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fee
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer fee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.freight_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer freightWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.collection_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer collectionWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.bank_code
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.card_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String cardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer soWay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.fa_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String faName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String soName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_point_sub_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private String soPointSubName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_point_sub_money
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer soPointSubMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.so_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Date soTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.collection_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Date collectionTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fa_invoice.cargo_num
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private Integer cargoNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.id
	 * @return  the value of fa_invoice.id
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.id
	 * @param id  the value for fa_invoice.id
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_no
	 * @return  the value of fa_invoice.fa_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getFaNo() {
		return faNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_no
	 * @param faNo  the value for fa_invoice.fa_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaNo(String faNo) {
		this.faNo = faNo == null ? null : faNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_time
	 * @return  the value of fa_invoice.fa_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Date getFaTime() {
		return faTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_time
	 * @param faTime  the value for fa_invoice.fa_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaTime(Date faTime) {
		this.faTime = faTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_phone
	 * @return  the value of fa_invoice.fa_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getFaPhone() {
		return faPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_phone
	 * @param faPhone  the value for fa_invoice.fa_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaPhone(String faPhone) {
		this.faPhone = faPhone == null ? null : faPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_point
	 * @return  the value of fa_invoice.fa_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Long getFaPoint() {
		return faPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_point
	 * @param faPoint  the value for fa_invoice.fa_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaPoint(Long faPoint) {
		this.faPoint = faPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_clientele
	 * @return  the value of fa_invoice.fa_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Long getFaClientele() {
		return faClientele;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_clientele
	 * @param faClientele  the value for fa_invoice.fa_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaClientele(Long faClientele) {
		this.faClientele = faClientele;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_phone
	 * @return  the value of fa_invoice.so_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getSoPhone() {
		return soPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_phone
	 * @param soPhone  the value for fa_invoice.so_phone
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoPhone(String soPhone) {
		this.soPhone = soPhone == null ? null : soPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_clientele
	 * @return  the value of fa_invoice.so_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Long getSoClientele() {
		return soClientele;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_clientele
	 * @param soClientele  the value for fa_invoice.so_clientele
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoClientele(Long soClientele) {
		this.soClientele = soClientele;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_point
	 * @return  the value of fa_invoice.so_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Long getSoPoint() {
		return soPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_point
	 * @param soPoint  the value for fa_invoice.so_point
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoPoint(Long soPoint) {
		this.soPoint = soPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.freight
	 * @return  the value of fa_invoice.freight
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getFreight() {
		return freight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.freight
	 * @param freight  the value for fa_invoice.freight
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFreight(Integer freight) {
		this.freight = freight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.collection
	 * @return  the value of fa_invoice.collection
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getCollection() {
		return collection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.collection
	 * @param collection  the value for fa_invoice.collection
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCollection(Integer collection) {
		this.collection = collection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.ins_time
	 * @return  the value of fa_invoice.ins_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Date getInsTime() {
		return insTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.ins_time
	 * @param insTime  the value for fa_invoice.ins_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setInsTime(Date insTime) {
		this.insTime = insTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.up_time
	 * @return  the value of fa_invoice.up_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.up_time
	 * @param upTime  the value for fa_invoice.up_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.status
	 * @return  the value of fa_invoice.status
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.status
	 * @param status  the value for fa_invoice.status
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.count_insurance
	 * @return  the value of fa_invoice.count_insurance
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getCountInsurance() {
		return countInsurance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.count_insurance
	 * @param countInsurance  the value for fa_invoice.count_insurance
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCountInsurance(Integer countInsurance) {
		this.countInsurance = countInsurance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fee
	 * @return  the value of fa_invoice.fee
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getFee() {
		return fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fee
	 * @param fee  the value for fa_invoice.fee
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFee(Integer fee) {
		this.fee = fee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.freight_way
	 * @return  the value of fa_invoice.freight_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getFreightWay() {
		return freightWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.freight_way
	 * @param freightWay  the value for fa_invoice.freight_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFreightWay(Integer freightWay) {
		this.freightWay = freightWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.collection_way
	 * @return  the value of fa_invoice.collection_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getCollectionWay() {
		return collectionWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.collection_way
	 * @param collectionWay  the value for fa_invoice.collection_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCollectionWay(Integer collectionWay) {
		this.collectionWay = collectionWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.bank_code
	 * @return  the value of fa_invoice.bank_code
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.bank_code
	 * @param bankCode  the value for fa_invoice.bank_code
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode == null ? null : bankCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.card_no
	 * @return  the value of fa_invoice.card_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.card_no
	 * @param cardNo  the value for fa_invoice.card_no
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo == null ? null : cardNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_way
	 * @return  the value of fa_invoice.so_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getSoWay() {
		return soWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_way
	 * @param soWay  the value for fa_invoice.so_way
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoWay(Integer soWay) {
		this.soWay = soWay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.fa_name
	 * @return  the value of fa_invoice.fa_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getFaName() {
		return faName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.fa_name
	 * @param faName  the value for fa_invoice.fa_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setFaName(String faName) {
		this.faName = faName == null ? null : faName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_name
	 * @return  the value of fa_invoice.so_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getSoName() {
		return soName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_name
	 * @param soName  the value for fa_invoice.so_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoName(String soName) {
		this.soName = soName == null ? null : soName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_point_sub_name
	 * @return  the value of fa_invoice.so_point_sub_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public String getSoPointSubName() {
		return soPointSubName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_point_sub_name
	 * @param soPointSubName  the value for fa_invoice.so_point_sub_name
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoPointSubName(String soPointSubName) {
		this.soPointSubName = soPointSubName == null ? null : soPointSubName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_point_sub_money
	 * @return  the value of fa_invoice.so_point_sub_money
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getSoPointSubMoney() {
		return soPointSubMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_point_sub_money
	 * @param soPointSubMoney  the value for fa_invoice.so_point_sub_money
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoPointSubMoney(Integer soPointSubMoney) {
		this.soPointSubMoney = soPointSubMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.so_time
	 * @return  the value of fa_invoice.so_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Date getSoTime() {
		return soTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.so_time
	 * @param soTime  the value for fa_invoice.so_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setSoTime(Date soTime) {
		this.soTime = soTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.collection_time
	 * @return  the value of fa_invoice.collection_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Date getCollectionTime() {
		return collectionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.collection_time
	 * @param collectionTime  the value for fa_invoice.collection_time
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCollectionTime(Date collectionTime) {
		this.collectionTime = collectionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fa_invoice.cargo_num
	 * @return  the value of fa_invoice.cargo_num
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public Integer getCargoNum() {
		return cargoNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fa_invoice.cargo_num
	 * @param cargoNum  the value for fa_invoice.cargo_num
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	public void setCargoNum(Integer cargoNum) {
		this.cargoNum = cargoNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		FaInvoice other = (FaInvoice) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getFaNo() == null ? other.getFaNo() == null : this
						.getFaNo().equals(other.getFaNo()))
				&& (this.getFaTime() == null ? other.getFaTime() == null : this
						.getFaTime().equals(other.getFaTime()))
				&& (this.getFaPhone() == null ? other.getFaPhone() == null
						: this.getFaPhone().equals(other.getFaPhone()))
				&& (this.getFaPoint() == null ? other.getFaPoint() == null
						: this.getFaPoint().equals(other.getFaPoint()))
				&& (this.getFaClientele() == null ? other.getFaClientele() == null
						: this.getFaClientele().equals(other.getFaClientele()))
				&& (this.getSoPhone() == null ? other.getSoPhone() == null
						: this.getSoPhone().equals(other.getSoPhone()))
				&& (this.getSoClientele() == null ? other.getSoClientele() == null
						: this.getSoClientele().equals(other.getSoClientele()))
				&& (this.getSoPoint() == null ? other.getSoPoint() == null
						: this.getSoPoint().equals(other.getSoPoint()))
				&& (this.getFreight() == null ? other.getFreight() == null
						: this.getFreight().equals(other.getFreight()))
				&& (this.getCollection() == null ? other.getCollection() == null
						: this.getCollection().equals(other.getCollection()))
				&& (this.getInsTime() == null ? other.getInsTime() == null
						: this.getInsTime().equals(other.getInsTime()))
				&& (this.getUpTime() == null ? other.getUpTime() == null : this
						.getUpTime().equals(other.getUpTime()))
				&& (this.getStatus() == null ? other.getStatus() == null : this
						.getStatus().equals(other.getStatus()))
				&& (this.getCountInsurance() == null ? other
						.getCountInsurance() == null : this.getCountInsurance()
						.equals(other.getCountInsurance()))
				&& (this.getFee() == null ? other.getFee() == null : this
						.getFee().equals(other.getFee()))
				&& (this.getFreightWay() == null ? other.getFreightWay() == null
						: this.getFreightWay().equals(other.getFreightWay()))
				&& (this.getCollectionWay() == null ? other.getCollectionWay() == null
						: this.getCollectionWay().equals(
								other.getCollectionWay()))
				&& (this.getBankCode() == null ? other.getBankCode() == null
						: this.getBankCode().equals(other.getBankCode()))
				&& (this.getCardNo() == null ? other.getCardNo() == null : this
						.getCardNo().equals(other.getCardNo()))
				&& (this.getSoWay() == null ? other.getSoWay() == null : this
						.getSoWay().equals(other.getSoWay()))
				&& (this.getFaName() == null ? other.getFaName() == null : this
						.getFaName().equals(other.getFaName()))
				&& (this.getSoName() == null ? other.getSoName() == null : this
						.getSoName().equals(other.getSoName()))
				&& (this.getSoPointSubName() == null ? other
						.getSoPointSubName() == null : this.getSoPointSubName()
						.equals(other.getSoPointSubName()))
				&& (this.getSoPointSubMoney() == null ? other
						.getSoPointSubMoney() == null : this
						.getSoPointSubMoney()
						.equals(other.getSoPointSubMoney()))
				&& (this.getSoTime() == null ? other.getSoTime() == null : this
						.getSoTime().equals(other.getSoTime()))
				&& (this.getCollectionTime() == null ? other
						.getCollectionTime() == null : this.getCollectionTime()
						.equals(other.getCollectionTime()))
				&& (this.getCargoNum() == null ? other.getCargoNum() == null
						: this.getCargoNum().equals(other.getCargoNum()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fa_invoice
	 * @mbggenerated  Sun Sep 06 22:04:08 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getFaNo() == null) ? 0 : getFaNo().hashCode());
		result = prime * result
				+ ((getFaTime() == null) ? 0 : getFaTime().hashCode());
		result = prime * result
				+ ((getFaPhone() == null) ? 0 : getFaPhone().hashCode());
		result = prime * result
				+ ((getFaPoint() == null) ? 0 : getFaPoint().hashCode());
		result = prime
				* result
				+ ((getFaClientele() == null) ? 0 : getFaClientele().hashCode());
		result = prime * result
				+ ((getSoPhone() == null) ? 0 : getSoPhone().hashCode());
		result = prime
				* result
				+ ((getSoClientele() == null) ? 0 : getSoClientele().hashCode());
		result = prime * result
				+ ((getSoPoint() == null) ? 0 : getSoPoint().hashCode());
		result = prime * result
				+ ((getFreight() == null) ? 0 : getFreight().hashCode());
		result = prime * result
				+ ((getCollection() == null) ? 0 : getCollection().hashCode());
		result = prime * result
				+ ((getInsTime() == null) ? 0 : getInsTime().hashCode());
		result = prime * result
				+ ((getUpTime() == null) ? 0 : getUpTime().hashCode());
		result = prime * result
				+ ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime
				* result
				+ ((getCountInsurance() == null) ? 0 : getCountInsurance()
						.hashCode());
		result = prime * result
				+ ((getFee() == null) ? 0 : getFee().hashCode());
		result = prime * result
				+ ((getFreightWay() == null) ? 0 : getFreightWay().hashCode());
		result = prime
				* result
				+ ((getCollectionWay() == null) ? 0 : getCollectionWay()
						.hashCode());
		result = prime * result
				+ ((getBankCode() == null) ? 0 : getBankCode().hashCode());
		result = prime * result
				+ ((getCardNo() == null) ? 0 : getCardNo().hashCode());
		result = prime * result
				+ ((getSoWay() == null) ? 0 : getSoWay().hashCode());
		result = prime * result
				+ ((getFaName() == null) ? 0 : getFaName().hashCode());
		result = prime * result
				+ ((getSoName() == null) ? 0 : getSoName().hashCode());
		result = prime
				* result
				+ ((getSoPointSubName() == null) ? 0 : getSoPointSubName()
						.hashCode());
		result = prime
				* result
				+ ((getSoPointSubMoney() == null) ? 0 : getSoPointSubMoney()
						.hashCode());
		result = prime * result
				+ ((getSoTime() == null) ? 0 : getSoTime().hashCode());
		result = prime
				* result
				+ ((getCollectionTime() == null) ? 0 : getCollectionTime()
						.hashCode());
		result = prime * result
				+ ((getCargoNum() == null) ? 0 : getCargoNum().hashCode());
		return result;
	}

	private List<CargoDetails> cargoDetailsSet;
	private SysPoint sysPointF;
	private SysPoint sysPointS;
	
	private BasClientele basClienteleF;
	private BasClientele basClienteleS;
	
	public List<CargoDetails> getCargoDetailsSet() {
		return cargoDetailsSet;
	}

	public void setCargoDetailsSet(List<CargoDetails> cargoDetailsSet) {
		this.cargoDetailsSet = cargoDetailsSet;
	}

	public SysPoint getSysPointF() {
		return sysPointF;
	}

	public void setSysPointF(SysPoint sysPointF) {
		this.sysPointF = sysPointF;
	}

	public SysPoint getSysPointS() {
		return sysPointS;
	}

	public void setSysPointS(SysPoint sysPointS) {
		this.sysPointS = sysPointS;
	}

	public BasClientele getBasClienteleF() {
		return basClienteleF;
	}

	public void setBasClienteleF(BasClientele basClienteleF) {
		this.basClienteleF = basClienteleF;
	}

	public BasClientele getBasClienteleS() {
		return basClienteleS;
	}

	public void setBasClienteleS(BasClientele basClienteleS) {
		this.basClienteleS = basClienteleS;
	}
	
}