package com.isatk.model.dto;

import java.io.Serializable;

public class SysPoint implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_point.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_point.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_point.mobile
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_point.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Integer isFa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_point.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private Integer isSo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_point
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_point.id
	 * @return  the value of sys_point.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_point.id
	 * @param id  the value for sys_point.id
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_point.name
	 * @return  the value of sys_point.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_point.name
	 * @param name  the value for sys_point.name
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_point.mobile
	 * @return  the value of sys_point.mobile
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_point.mobile
	 * @param mobile  the value for sys_point.mobile
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_point.is_fa
	 * @return  the value of sys_point.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Integer getIsFa() {
		return isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_point.is_fa
	 * @param isFa  the value for sys_point.is_fa
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setIsFa(Integer isFa) {
		this.isFa = isFa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_point.is_so
	 * @return  the value of sys_point.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Integer getIsSo() {
		return isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_point.is_so
	 * @param isSo  the value for sys_point.is_so
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setIsSo(Integer isSo) {
		this.isSo = isSo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_point
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		SysPoint other = (SysPoint) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null : this
						.getName().equals(other.getName()))
				&& (this.getMobile() == null ? other.getMobile() == null : this
						.getMobile().equals(other.getMobile()))
				&& (this.getIsFa() == null ? other.getIsFa() == null : this
						.getIsFa().equals(other.getIsFa()))
				&& (this.getIsSo() == null ? other.getIsSo() == null : this
						.getIsSo().equals(other.getIsSo()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_point
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getMobile() == null) ? 0 : getMobile().hashCode());
		result = prime * result
				+ ((getIsFa() == null) ? 0 : getIsFa().hashCode());
		result = prime * result
				+ ((getIsSo() == null) ? 0 : getIsSo().hashCode());
		return result;
	}
}