package com.isatk.model.dto;

import com.isatk.model.bean.Page;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected Page page;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public SysUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public void setPage(Page page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public Page getPage() {
		return page;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andFaRangeIsNull() {
			addCriterion("fa_range is null");
			return (Criteria) this;
		}

		public Criteria andFaRangeIsNotNull() {
			addCriterion("fa_range is not null");
			return (Criteria) this;
		}

		public Criteria andFaRangeEqualTo(Long value) {
			addCriterion("fa_range =", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeNotEqualTo(Long value) {
			addCriterion("fa_range <>", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeGreaterThan(Long value) {
			addCriterion("fa_range >", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeGreaterThanOrEqualTo(Long value) {
			addCriterion("fa_range >=", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeLessThan(Long value) {
			addCriterion("fa_range <", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeLessThanOrEqualTo(Long value) {
			addCriterion("fa_range <=", value, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeIn(List<Long> values) {
			addCriterion("fa_range in", values, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeNotIn(List<Long> values) {
			addCriterion("fa_range not in", values, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeBetween(Long value1, Long value2) {
			addCriterion("fa_range between", value1, value2, "faRange");
			return (Criteria) this;
		}

		public Criteria andFaRangeNotBetween(Long value1, Long value2) {
			addCriterion("fa_range not between", value1, value2, "faRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeIsNull() {
			addCriterion("so_range is null");
			return (Criteria) this;
		}

		public Criteria andSoRangeIsNotNull() {
			addCriterion("so_range is not null");
			return (Criteria) this;
		}

		public Criteria andSoRangeEqualTo(Long value) {
			addCriterion("so_range =", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeNotEqualTo(Long value) {
			addCriterion("so_range <>", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeGreaterThan(Long value) {
			addCriterion("so_range >", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeGreaterThanOrEqualTo(Long value) {
			addCriterion("so_range >=", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeLessThan(Long value) {
			addCriterion("so_range <", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeLessThanOrEqualTo(Long value) {
			addCriterion("so_range <=", value, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeIn(List<Long> values) {
			addCriterion("so_range in", values, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeNotIn(List<Long> values) {
			addCriterion("so_range not in", values, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeBetween(Long value1, Long value2) {
			addCriterion("so_range between", value1, value2, "soRange");
			return (Criteria) this;
		}

		public Criteria andSoRangeNotBetween(Long value1, Long value2) {
			addCriterion("so_range not between", value1, value2, "soRange");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("login_name is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("login_name is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("login_name =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("login_name <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("login_name >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("login_name >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("login_name <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("login_name <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("login_name like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("login_name not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("login_name in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("login_name not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("login_name between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("login_name not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andPwdIsNull() {
			addCriterion("pwd is null");
			return (Criteria) this;
		}

		public Criteria andPwdIsNotNull() {
			addCriterion("pwd is not null");
			return (Criteria) this;
		}

		public Criteria andPwdEqualTo(String value) {
			addCriterion("pwd =", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotEqualTo(String value) {
			addCriterion("pwd <>", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThan(String value) {
			addCriterion("pwd >", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThanOrEqualTo(String value) {
			addCriterion("pwd >=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThan(String value) {
			addCriterion("pwd <", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThanOrEqualTo(String value) {
			addCriterion("pwd <=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLike(String value) {
			addCriterion("pwd like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotLike(String value) {
			addCriterion("pwd not like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdIn(List<String> values) {
			addCriterion("pwd in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotIn(List<String> values) {
			addCriterion("pwd not in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdBetween(String value1, String value2) {
			addCriterion("pwd between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotBetween(String value1, String value2) {
			addCriterion("pwd not between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andInsTimeIsNull() {
			addCriterion("ins_time is null");
			return (Criteria) this;
		}

		public Criteria andInsTimeIsNotNull() {
			addCriterion("ins_time is not null");
			return (Criteria) this;
		}

		public Criteria andInsTimeEqualTo(Date value) {
			addCriterion("ins_time =", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotEqualTo(Date value) {
			addCriterion("ins_time <>", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeGreaterThan(Date value) {
			addCriterion("ins_time >", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ins_time >=", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeLessThan(Date value) {
			addCriterion("ins_time <", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeLessThanOrEqualTo(Date value) {
			addCriterion("ins_time <=", value, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeIn(List<Date> values) {
			addCriterion("ins_time in", values, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotIn(List<Date> values) {
			addCriterion("ins_time not in", values, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeBetween(Date value1, Date value2) {
			addCriterion("ins_time between", value1, value2, "insTime");
			return (Criteria) this;
		}

		public Criteria andInsTimeNotBetween(Date value1, Date value2) {
			addCriterion("ins_time not between", value1, value2, "insTime");
			return (Criteria) this;
		}

		public Criteria andIsDisableIsNull() {
			addCriterion("is_disable is null");
			return (Criteria) this;
		}

		public Criteria andIsDisableIsNotNull() {
			addCriterion("is_disable is not null");
			return (Criteria) this;
		}

		public Criteria andIsDisableEqualTo(Integer value) {
			addCriterion("is_disable =", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotEqualTo(Integer value) {
			addCriterion("is_disable <>", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableGreaterThan(Integer value) {
			addCriterion("is_disable >", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_disable >=", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableLessThan(Integer value) {
			addCriterion("is_disable <", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableLessThanOrEqualTo(Integer value) {
			addCriterion("is_disable <=", value, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableIn(List<Integer> values) {
			addCriterion("is_disable in", values, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotIn(List<Integer> values) {
			addCriterion("is_disable not in", values, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableBetween(Integer value1, Integer value2) {
			addCriterion("is_disable between", value1, value2, "isDisable");
			return (Criteria) this;
		}

		public Criteria andIsDisableNotBetween(Integer value1, Integer value2) {
			addCriterion("is_disable not between", value1, value2, "isDisable");
			return (Criteria) this;
		}

		public Criteria andNameLikeInsensitive(String value) {
			addCriterion("upper(name) like", value.toUpperCase(), "name");
			return (Criteria) this;
		}

		public Criteria andLoginNameLikeInsensitive(String value) {
			addCriterion("upper(login_name) like", value.toUpperCase(),
					"loginName");
			return (Criteria) this;
		}

		public Criteria andPwdLikeInsensitive(String value) {
			addCriterion("upper(pwd) like", value.toUpperCase(), "pwd");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_user
	 * @mbggenerated  Tue May 05 20:07:07 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bas_organize
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 10 16:36:02 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}